# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - master
      - dev
      - memory-fixes

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    sudo add-apt-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
    sudo apt-get update
    sudo apt-get install -y clang-format-8 clang-tidy-8
    sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-8 100
    echo "Beginning Linting"
    cp ./make.inc-examples/make.inc-standard ./make.inc
    make lint LINTER=clang-tidy-8
  displayName: 'lint'
